---
  servers:
    hosts:
      jenkins-master:
        ansible_host: 192.168.100.200
        ansible_ssh_private_key_file: /home/home/DevOps обучение/practice/Раздел_9/Practice_9.4/Vagrant/.vagrant/machines/clickhouse/virtualbox/private_key
      jenkins-agent:
        ansible_host: 192.168.100.201
        ansible_ssh_private_key_file: /home/home/DevOps обучение/practice/Раздел_9/Practice_9.4/Vagrant/.vagrant/machines/vector/virtualbox/private_key