---
all:
  hosts:
    jenkins-master:
      ansible_host: 192.168.100.200
      ansible_ssh_private_key_file: /home/home/.vagrant.d/machines/jenkins-master/virtualbox/private_key
    jenkins-agent:
      ansible_host: 192.168.100.201
      ansible_ssh_private_key_file: /home/home/.vagrant.d/machines/jenkins-agent/virtualbox/private_key
  children:
    jenkins:
      children:
        jenkins-masters:
          hosts:
            jenkins-master
        jenkins-agents:
          hosts:
            jenkins-agent
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant #${username}
