---
  - name: Add master publickey into authorized_key
    authorized_key:
      user: "{{ jenkins_user_name }}"
      state: present
#      key: "{{ hostvars['jenkins-master-0']['ssh_key_info']['ssh_public_key'] }}"
      key: "{{ hostvars['jenkins-master']['ssh_key_info']['ssh_public_key'] }}"

  - name: Create agent_dir
    become_user: root
    file:
      path: "{{ jenkins_agent_dir }}"
      state: directory
      owner: "{{ jenkins_user_name }}"
      group: "{{ jenkins_user_group }}"

  - name: Remove docker if installed from node
    apt:
      pkg:
        - docker
        - docker-*
      state: absent

  - name: Install required system packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
        - ansible*
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker
    ansible.builtin.apt:
      name:
        - docker
        - docker-ce
        - docker.io
        - docker-compose
        - docker-registry
      state: latest
      update_cache: true

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Add local to PATH
    lineinfile:
      dest: ~/.bashrc
      regexp: export PATH=$PATH:/home/jenkins/.local/bin
      line: export PATH=$PATH:/home/jenkins/.local/bin

  - name: Create docker group
    become_user: root
    group:
      name: docker
      state: present

  - name: Add jenkinsuser to dockergroup
    become_user: root
    user:
      name: "{{ jenkins_user_name }}"
      groups: docker
      append: true

  - name: Restart docker
    become_user: root
    systemd:
      name: docker
      state: restarted
      enabled: true

  - name: Install agent.jar
    get_url:
#      url: "http://{{ hostvars['jenkins-master-0']['ansible_host'] }}:8080/jnlpJars/agent.jar"
      url: "http://{{ hostvars['jenkins-master']['ansible_host'] }}:8080/jnlpJars/agent.jar"
      dest: "{{ jenkins_agent_dir }}"
    register: install_agent
    until: install_agent is succeeded
    retries: 10
    timeout: 10

  - name: Install Molecule python package on version 3.5.2
#    become_user: "{{ jenkins_user_name }}"
    become: true
    pip:
      name:
        - molecule
        - molecule-docker
      executable: pip3

  - name: Download Jenkins repository key
    shell: export PATH=$PATH:/home/jenkins/.local/bin
    changed_when: false
